# Generated by Django 5.1.6 on 2025-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото",
                null=True,
                upload_to="users/templates/users/media",
                verbose_name="Аватар",
            ),
        ),
    ]
